- name: Update brew cask versions
  shell: brew tap homebrew/cask-versions
- name: Install Hombrew Cask apps
  community.general.homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items: "{{ homebrew_cask }}"
- name: Install Homebrew apps 
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  with_items: "{{ homebrew }}"
  tags:
    - install